Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_2'
srun: error: cn131: tasks 0-1,11,18,20,25-26,28-29,35,43-44: Exited with exit code 1
slurmstepd: error: *** STEP 34361.0 ON cn131 CANCELLED AT 2020-02-18T12:36:08 ***
slurmstepd: error: *** JOB 34361 ON cn131 CANCELLED AT 2020-02-18T12:36:08 ***
