Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_9'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_9'
Traceback (most recent call last):
  File "/home/collins/Param_test/initExperiment.py", line 27, in <module>
    os.makedirs(folder)
  File "/home/apps/anaconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/collins/Simulation_Data/Wide_EIB_GABAALNPN_0.5/OdorA_High_Dur_6000_OdorDur_1000_Locust_A_9'
srun: error: cn091: tasks 1,10,16: Exited with exit code 1
Traceback (most recent call last):
  File "/home/collins/Param_test/receptorLayer.py", line 102, in <module>
    random_normal = np.random.normal(size=orns.shape)
  File "mtrand.pyx", line 1484, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 558, in numpy.random._common.cont
MemoryError: Unable to allocate 4.47 GiB for an array with shape (1000, 600000) and data type float64
slurmstepd: error: *** JOB 34358 ON cn091 CANCELLED AT 2020-02-18T12:36:07 ***
slurmstepd: error: *** STEP 34358.0 ON cn091 CANCELLED AT 2020-02-18T12:36:07 ***
